// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns process liveness status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/league/next-week": {
            "post": {
                "description": "Simulates the next week's matches and updates state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Simulate next week",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/league/overview": {
            "get": {
                "description": "Returns the current league table, weekly match status, and predictions when available",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Get league overview",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LeagueOverview"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/league/play-all": {
            "post": {
                "description": "Simulates all remaining matches in the season",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Play all remaining weeks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/league/reset": {
            "post": {
                "description": "Resets the entire league to initial state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Reset league",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/league/rollback/{week}": {
            "post": {
                "description": "Reverts database state to a specific week",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Rollback league state",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Week to rollback to",
                        "name": "week",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/league/table": {
            "get": {
                "description": "Returns current league standings (PTS, W, D, L, GD)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Get current standings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/matches/{id}": {
            "get": {
                "description": "Returns a specific match and its events",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Get match details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    }
                }
            },
            "put": {
                "description": "Edits a specific match result; recalculates standings and morale",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Edit match result",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Edited score",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.EditMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/simulation/championship-probabilities": {
            "get": {
                "description": "Runs 1,000 Monte Carlo simulations to calculate Championship Win %",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "simulation"
                ],
                "summary": "Championship probabilities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/teams/{id}/metrics": {
            "get": {
                "description": "Returns a team's current Strength, Morale, Fatigue, and Market Value",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Get team metrics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TeamMetrics"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProblemDetails"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.EditMatchRequest": {
            "type": "object",
            "properties": {
                "away_score": {
                    "type": "integer",
                    "example": 1
                },
                "home_score": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "handlers.ProblemDetails": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Stable machine-readable error code",
                    "type": "string"
                },
                "detail": {
                    "description": "Human-readable explanation specific to this occurrence",
                    "type": "string"
                },
                "instance": {
                    "description": "URI reference that identifies the specific occurrence",
                    "type": "string"
                },
                "status": {
                    "description": "HTTP status code",
                    "type": "integer"
                },
                "title": {
                    "description": "Short, human-readable summary",
                    "type": "string"
                },
                "type": {
                    "description": "URI reference that identifies the problem type",
                    "type": "string"
                }
            }
        },
        "models.LeagueOverview": {
            "type": "object",
            "properties": {
                "current_week": {
                    "type": "integer"
                },
                "predictions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Prediction"
                    }
                },
                "standings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Standing"
                    }
                },
                "weeks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WeekResult"
                    }
                }
            }
        },
        "models.Match": {
            "type": "object",
            "properties": {
                "away_score": {
                    "description": "nil if not played",
                    "type": "integer"
                },
                "away_team": {
                    "type": "string"
                },
                "away_team_id": {
                    "type": "integer"
                },
                "home_score": {
                    "description": "nil if not played",
                    "type": "integer"
                },
                "home_team": {
                    "type": "string"
                },
                "home_team_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "description": "scheduled, played, edited",
                    "type": "string"
                },
                "weather_condition": {
                    "description": "sunny, rainy, snowy, windy, foggy",
                    "type": "string"
                },
                "week": {
                    "type": "integer"
                }
            }
        },
        "models.Prediction": {
            "type": "object",
            "properties": {
                "championship_win_pct": {
                    "type": "number"
                },
                "team_id": {
                    "type": "integer"
                },
                "team_name": {
                    "type": "string"
                }
            }
        },
        "models.Standing": {
            "type": "object",
            "properties": {
                "drawn": {
                    "type": "integer"
                },
                "ga": {
                    "description": "goals against",
                    "type": "integer"
                },
                "gd": {
                    "description": "goal difference",
                    "type": "integer"
                },
                "gf": {
                    "description": "goals for",
                    "type": "integer"
                },
                "lost": {
                    "type": "integer"
                },
                "played": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                },
                "position": {
                    "type": "integer"
                },
                "team_id": {
                    "type": "integer"
                },
                "team_name": {
                    "type": "string"
                },
                "won": {
                    "type": "integer"
                }
            }
        },
        "models.TeamMetrics": {
            "type": "object",
            "properties": {
                "base_strength": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "current_strength": {
                    "type": "integer"
                },
                "fatigue": {
                    "type": "number"
                },
                "market_value": {
                    "type": "number"
                },
                "morale": {
                    "type": "number"
                },
                "team_id": {
                    "type": "integer"
                },
                "team_name": {
                    "type": "string"
                }
            }
        },
        "models.WeekResult": {
            "type": "object",
            "properties": {
                "matches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Match"
                    }
                },
                "week": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Football League Simulation API",
	Description:      "REST API for simulating a four-team football league, editing match results, rolling back state, and calculating championship probabilities.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
